sudo: required

services:
  - docker

## Make sure all containers build without error.
before_install: 
  - docker build -t soulmachine/gitbook gitbook
  - docker build -t soulmachine/hexo hexo
  - docker build -t soulmachine/markdown2confluence markdown2confluence
  - docker build -t soulmachine/openjdk openjdk
  - docker build -t soulmachine/r-base r-base
  - docker build -t soulmachine/rstudio rstudio
  - docker build -t soulmachine/shellcheck shellcheck
  - docker build -t soulmachine/spark-base spark/spark-base/from-source
  - docker build -t soulmachine/spark-master spark/spark-master
  - docker build -t soulmachine/spark-worker spark/spark-worker
  - docker build -t soulmachine/apache-zeppelin apache-zeppelin

## A few simple / crude tests
script:
  - docker run --rm -it soulmachine/gitbook --version
  - docker run --rm -it soulmachine/hexo --version
  - docker run --rm -it soulmachine/openjdk javac -version
  - docker run --rm -it soulmachine/r-base R --version
  - docker run -d --name rstudio soulmachine/rstudio
  - sleep 5 && docker ps | grep rstudio
  - docker rm -f $(docker ps -a -q)
  - docker run --rm -it soulmachine/shellcheck --version
  - cd spark/ && docker-compose up -d
  - sleep 5 && docker ps | grep spark-master
  - sleep 5 && curl -s http://localhost:8080 | grep ALIVE
  - docker-compose down

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/gitbook
  - docker push $DOCKER_USERNAME/hexo
  - docker push $DOCKER_USERNAME/markdown2confluence
  - docker push $DOCKER_USERNAME/openjdk
  - docker push $DOCKER_USERNAME/r-base
  - docker push $DOCKER_USERNAME/rstudio
  - docker push $DOCKER_USERNAME/shellcheck
  - docker push $DOCKER_USERNAME/spark-base
  - docker push $DOCKER_USERNAME/spark-master
  - docker push $DOCKER_USERNAME/spark-worker
  - docker push $DOCKER_USERNAME/apache-zeppelin

