version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: elasticsearch
    environment:
      - cluster.name=elastic-cluster
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata_elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.2
    container_name: kibana
    volumes:
      - esdata_kibana:/usr/share/kibana/data
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata_elastic:
    driver: local
  esdata_kibana:
    driver: local

networks:
  esnet:
